"""empty message

Revision ID: 043c06874a7f
Revises: 
Create Date: 2025-01-23 19:15:44.537283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043c06874a7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('altura', sa.String(length=120), nullable=False),
    sa.Column('color_de_pelo', sa.String(length=80), nullable=True),
    sa.Column('color_de_ojos', sa.String(length=80), nullable=True),
    sa.Column('genero', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poblacion', sa.String(length=120), nullable=False),
    sa.Column('terreno', sa.String(length=80), nullable=False),
    sa.Column('admosfera', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('personajes_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    op.drop_table('user')
    op.drop_table('planetas')
    op.drop_table('personaje')
    # ### end Alembic commands ###
